all:
  children:
    production:
      hosts:
        HOST1:
          site_domain: "{{ inventory_hostname }}"
          letsencrypt_email: mail@example.com
          wordpress_theme:
            - name: THEMENAME # e.g. 'oceanwp'
              version: THEMEVERSION # e.g. '1.8.9'
              child_theme_file: CHILD_THEME_FILE # if provided in ./roles/wordpress/files
          wordpress_plugins:
            # use plugin name from wordpress route 
            # e.g. https://wordpress.org/plugins/LOOK-HERE-FOR-PLUGIN-NAME/
            - name: WP_PLUGIN_NAME_A
            - name: WP_PLUGIN_NAME_B
            - name: WP_PLUGIN_NAME_C
    develop:
      hosts:
        HOST2:
          site_domain: "{{ inventory_hostname }}"
          letsencrypt_email: mail@example.com
          wordpress_theme:
            - name: THEMENAME # e.g. 'oceanwp'
              version: THEMEVERSION # e.g. '1.8.9'
              child_theme_file: CHILD_THEME_FILE # if provided in ./roles/wordpress/files
          wordpress_plugins:
            - name: WP_PLUGIN_NAME
