---
- name: ensure mariadb and deps are installed
  dnf:
    name: ["mariadb", "mariadb-server", "python3"]
    state: present
    update_cache: yes

- name: make sure pymysql is present
  become: true
  pip:
    name: pymysql
    state: present

- name: set ulimit in mariadb.service
  lineinfile:
    path: /usr/lib/systemd/system/mariadb.service
    insertafter: '\[Service\]'
    line: "LimitNOFILE=infinity"
    state: present
  notify: restart mariadb

- name: copy my.cnf file
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
  notify: restart mariadb

- name: ensure mariadb service is enabled and running
  service:
    name: mariadb
    state: started
    enabled: yes

- name: check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ hosts_vault[inventory_hostname].db_password_root }}"
    host: localhost
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
  when: root_pwd_check.rc == 0

- name: set MariaDB root password for 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ hosts_vault[inventory_hostname].db_password_root }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ hosts_vault[inventory_hostname].db_password_root }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc == 0

- name: remove the test database
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ hosts_vault[inventory_hostname].db_password_root }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: absent

- name: create wordpress database
  mysql_db:
    name: "{{ db_name }}"
    login_user: root
    login_password: "{{ hosts_vault[inventory_hostname].db_password_root }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    state: present
  register: db_creation

- name: create Wordpress database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ hosts_vault[inventory_hostname].db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: localhost
    state: present
    login_user: root
    login_password: "{{ hosts_vault[inventory_hostname].db_password_root }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
